version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "customers"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
    - "db:/var/lib/postgresql"
    ports:
    - "25432:5432"

volumes:
  db: {}
