version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "customers"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
    - "db:/var/lib/postgresql"
    ports:
    - "25432:5432"
  nats:
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    hostname: nats-server

volumes:
  db: {}
